apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: echo-cert
spec:
  secretName: echo-cert
  dnsNames:
    - "kaspa-chain.net"
  issuerRef:
    name: lets-encrypt-issuer-prod-http
    kind: ClusterIssuer
    group: cert-manager.io
